__title__ = '{{cookiecutter.project_name}}'
__description__ = '{{cookiecutter.project_short_description}}'
__url__ = 'https://github.com/dbt-ethz/{{cookiecutter.project_slug}}'
__version__ = '{{cookiecutter.version}}'
__author__ = 'Digital Building Technologies'
__author_email__ = 'dbt@arch.ethz.ch'
__license__ = 'MIT license'
__copyright__ = 'Copyright {% now 'utc', '%Y' %} Digital Building Technologies'
